### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by neoOpus** [Roshan-R/PyDrop#7]
Hi,

Is there any plan to adopt this to Windows 10/11?

This seems superior to all the alternative and Windows environment lacks a good productivity tool like this.

**Comment by Roshan-R** [comment]
Thanks for your interest in PyDrop
I had previously tried to build this in windows but the Drag and Drop functionality was broken which I suspect was an issue of Gtk and not of PyDrop.
I'd ultimately like to port this to windows one day when the bug gets fixed, meanwhile   
check out [this windows alternative](https://github.com/GameGodS3/DropPoint)

**Comment by neoOpus** [comment]
OK Thanks
